// app/javascript/controllers/index.js
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
//   ./bin/rails generate stimulus <controllerName>
// もしくは手で編集したら、再度 manifest:update を実行してください。

import { application } from "./application"

// まとめて更新用（バッファ）のコントローラ
import LineupController from "./lineup_controller"
application.register("lineup", LineupController)

// （任意）個別スロット操作など、別途使う場合のコントローラ
import MatchEditorController from "./match_editor_controller"
application.register("match-editor", MatchEditorController)